#!/usr/bin/perl

# Copyright © 2018 Rafael Laboisière <rafael@debian.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.

=encoding utf8

=head1 NAME

dh_octave_changelogs - install symlinks to Octave-Forge package documentation

=head1 SYNOPSIS

B<dh_octave_changelogs>

=head1 DESCRIPTION

B<dh_octave_changelogs> is intended to be run from the
top-level source directory of an Octave add-on package.  It installs
symlinks for the upstream files F<NEWS> and F<ChangeLog>.

=head1 SEE ALSO

L<debhelper(7)>, L<dh(1)>, L<dh_octave_substvar(1)>,
L<dh_octave_clean(1)>, L<dh_octave_check(1)>, L<dh_octave_version(1)>,
L<dh_octave_examples(1)>

This program is meant to be used together with debhelper for Debian
packages derived from Octave-Forge packages.
It is recommended to enable it by adding the dh-sequence-octave
virtual package to Build-Depends, Build-Depends-Arch or
Build-Depends-Indep.
This is equivalent to adding dh-octave to the same field and adding
--with=octave to the dh sequencer in debian/rules, except that only
-arch/-indep/profiled builds are affected.

=head1 AUTHOR

Rafael Laboissière <rafael@debian.org>

=cut

use Debian::Debhelper::Dh_Lib;

init ();

### Install symlinks for the NEWS and ChangeLog files

@pkgs = @{$dh{DOPACKAGES}};

### Loop over all binary packages
for $p (@pkgs) {
    ## Directory for looking for the upstream changelog
    $d = "debian/$p/usr/share/octave";
    next if ! -d $d;
    ## Look for it
    $out = qx{find $d -name "NEWS"};
    chomp $out;

    if ($out ne "") {
	## Link to the /usr/share/doc dir, with appropriate name
        $out =~ s:debian/$p/usr/share/::;
        doit ("ln", "-fs", "../../$out",
              "debian/$pkgs[0]/usr/share/doc/$pkgs[0]/");
	## Do it only once
        last;
    }
}

### Loop over all binary packages
for $p (@pkgs) {
    ## Remove upstream changelog installed by dh_installchangelogs
    doit ("rm", "-rf", "debian/$p/usr/share/doc/$p/changelog");
    ## Directory where to look for the upstream changelog
    $d = "debian/$p/usr/share/octave";
    next if ! -d $d;
    ## Look for it
    $out = qx{find $d -name "ChangeLog"};
    chomp $out;

    if ($out ne "") {
	## Compress it
        doit ("gzip", "-9", $out);
	## Link to the /usr/share/doc dir, with appropriate name
        $out =~ s:debian/$p/usr/share/::;
        doit ("ln", "-fs", "../../$out.gz",
              "debian/$pkgs[0]/usr/share/doc/$pkgs[0]/changelog.gz");
	## Do it only once
        last;
    }
}
